language: android
jdk: oraclejdk7

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Use extra android repo locations to find the appcompat-v7:21.0.3 support library
    - extra

    # Specify system image for emulation (needed to run unit tests)
    - sys-img-armeabi-v7a-android-21

# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - /usr/local/bin/android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &

script:
    - echo $ADB_INSTALL_TIMEOUT
    - android list target
    # Specify the build script to run
    - ./travis/build.sh

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

